version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongodb_data: